name: Docker Build and Push

on:
    push:
       branches:
           - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar mi repositorio
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}""

      - name: Crear la imagen Docker
        run: docker build -t jairo0624/music-api:latest .

      - name: Publicar la imagen Docker
        run: docker push jairo0624/music-api:latest

      